
version: '3'

services:
  db:
    image: postgres
    container_name: db-gobaber
    hostname: db-gobaber
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'docker'
    ports:
      - 5432:5432
volumes:
  postgres: